site_name: TCGA-COAD CMS ML Pipeline
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Inici: index.md
  - Execució: execucio.md
  - Dades i pipeline: pipeline.md
  - Experiments i resultats: resultats.md
  - Reproductibilitat i referència: referencia.md
  - Glossari: glossari.md